### ISSUE TITLE
Problem with displaying the UI

### ISSUE THREAD

**Issue by ALucas23** [ptal/lol2D#48]
This error produces problems in the visual output of the game. The problems are difficult to explain, but the UI is completly messed up by this error. The error happens on my PC 3-5 times per run.

Exception in thread "JavaFX Application Thread" java.lang.IllegalArgumentException: TilePane@36bb0132[styleClass=root]is already set as root of another scene
	at javafx.scene.Scene$9.invalidated(Scene.java:1110)
	at javafx.beans.property.ObjectPropertyBase.markInvalid(ObjectPropertyBase.java:111)
	at javafx.beans.property.ObjectPropertyBase.set(ObjectPropertyBase.java:146)
	at javafx.scene.Scene.setRoot(Scene.java:1072)
	at javafx.scene.Scene.<init>(Scene.java:347)
	at javafx.scene.Scene.<init>(Scene.java:194)
	at lol.ui.BattlefieldView.lambda$update$0(BattlefieldView.java:43)
	at com.sun.javafx.application.PlatformImpl.lambda$null$173(PlatformImpl.java:295)
	at java.security.AccessController.doPrivileged(Native Method)
	at com.sun.javafx.application.PlatformImpl.lambda$runLater$174(PlatformImpl.java:294)
	at com.sun.glass.ui.InvokeLaterDispatcher$Future.run(InvokeLaterDispatcher.java:95)
	at com.sun.glass.ui.win.WinApplication._runLoop(Native Method)
	at com.sun.glass.ui.win.WinApplication.lambda$null$148(WinApplication.java:191)
	at java.lang.Thread.run(Thread.java:748)

**Comment by ptal** [comment]
Does it still happen with the latest version?

**Comment by ALucas23** [comment]
has been fixed
